[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[inet_http_server]
port = 0.0.0.0:9001
username=admin
password=admin

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

# PROCES 1: PHP-FPM (utrzymuje działanie serwera WWW)
[program:php-fpm]
command=php-fpm8.5 -F
autostart=true
autorestart=true
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile=/var/log/php-fpm.out.log

# PROCES 2: Symfony Messenger Worker
[program:messenger-consume]
command=php /var/www/html/bin/console messenger:consume async --limit=50 --memory-limit=128M
user=www-data
numprocs=1
autostart=true
autorestart=true
stderr_logfile=/var/log/messenger.err.log
stdout_logfile=/var/log/messenger.out.log
